name: Python CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
      
    - name: Install dependencies
      run: |
       pip install flask
       pip install pytest
       pip install -e .   # ← installe ton package Depot
     
    - name: Install project
      run: pip install -e .

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV

    - name: Run tests
      run: PYTHONPATH=src pytest -v

